from __future__ import annotations

import json
import re
from pathlib import Path

from .models import Finding, Session
from .private_io import open_private_text
from .storage import Storage


def export_markdown(
    storage: Storage,
    session: Session,
    path: str | Path,
    executive_summary: str | None = None,
) -> Path:
    destination = Path(path).expanduser()
    destination.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    commands = storage.list_command_runs(session.id, limit=None)
    events = storage.list_events(session.id, limit=None)
    findings = storage.list_findings(session.id)

    lines: list[str] = [
        f"# Assessment report: {_markdown_inline(session.name)}",
        "",
        "Generated by The Wizard's Pick.",
        "",
    ]

    if executive_summary:
        lines.extend(["## Executive summary", "", _markdown_literal(executive_summary.strip()), ""])

    lines.extend(
        [
            "## Assessment context",
            "",
            f"- Session ID: `{session.id}`",
            f"- Created: {session.created_at}",
            f"- Updated: {session.updated_at}",
            f"- Mode: {session.mode.value}",
            f"- Target type: {_markdown_inline(session.scope.target_type)}",
            "- Targets/context: "
            + _markdown_inline(", ".join(session.scope.authorized_targets) or "none"),
            "- Excluded targets: "
            + _markdown_inline(", ".join(session.scope.excluded_targets) or "none"),
            "- Testing window: "
            + _markdown_inline(session.scope.testing_window or "not specified"),
            f"- Intensity: {_markdown_inline(session.scope.intensity)}",
            "- Focus areas: "
            + _markdown_inline(", ".join(session.scope.allowed_categories) or "none"),
            "- Authorization: "
            + _markdown_inline(session.scope.authorization_label or "operator managed"),
            "- Emergency contact: "
            + _markdown_inline(session.scope.emergency_contact or "not specified"),
            f"- Notes: {_markdown_inline(session.scope.notes or 'none')}",
            "",
            "## Findings",
            "",
        ]
    )

    if findings:
        for index, finding in enumerate(findings, start=1):
            lines.extend(_finding_lines(index, finding))
    else:
        lines.append("No findings have been recorded yet.")
        lines.append("")

    lines.extend(["## Command timeline", ""])
    if commands:
        for index, item in enumerate(commands, start=1):
            proposal = item["proposal"]
            result = item["result"]
            lines.extend(
                [
                    f"### {index}. {_markdown_inline(str(proposal.get('technique', 'Command')))}",
                    "",
                    f"- Status: {item['status']}",
                    f"- Risk: {proposal.get('risk_level', 'unknown')}",
                    f"- Created: {item['created_at']}",
                    "",
                    *_code_block(str(result.get("command", "")), "bash"),
                    "",
                ]
            )
            output = "\n".join(
                part.strip()
                for part in (result.get("stdout", ""), result.get("stderr", ""))
                if part.strip()
            ).strip()
            if output:
                lines.extend(["Output excerpt:", "", *_code_block(output[:4000], "text"), ""])
    else:
        lines.append("No commands have been executed through the assistant.")
        lines.append("")

    lines.extend(["## Audit events", ""])
    if events:
        for event in events:
            lines.extend(
                [
                    f"- {event['created_at']} `{event['kind']}`",
                    "",
                    *_code_block(json.dumps(event["data"], sort_keys=True), "json"),
                    "",
                ]
            )
    else:
        lines.append("No audit events have been recorded.")
    lines.append("")

    with open_private_text(destination) as report:
        report.write("\n".join(lines))
    return destination


def _code_block(content: str, language: str) -> list[str]:
    runs = [len(match.group()) for match in re.finditer(r"`+", content)]
    fence = "`" * max(3, max(runs, default=0) + 1)
    return [f"{fence}{language}", content, fence]


_MARKDOWN_SPECIALS = frozenset("\\`*_[]<>#+!|=~")


def _markdown_literal(content: str) -> str:
    return "".join(
        f"\\{character}" if character in _MARKDOWN_SPECIALS else character for character in content
    )


def _markdown_inline(content: str) -> str:
    return _markdown_literal(" ".join(content.split()))


def _finding_lines(index: int, finding: Finding) -> list[str]:
    return [
        f"### {index}. {_markdown_inline(finding.title)}",
        "",
        f"- Severity: {finding.severity.value}",
        f"- Classification: {_markdown_inline(finding.classification or 'not specified')}",
        f"- Difficulty: {_markdown_inline(finding.difficulty or 'not specified')}",
        "",
        "**Evidence**",
        "",
        _markdown_literal(finding.evidence or "No evidence recorded."),
        "",
        "**Business impact**",
        "",
        _markdown_literal(finding.business_impact or "Not specified."),
        "",
        "**Reproduction steps**",
        "",
        _markdown_literal(finding.reproduction_steps or "Not specified."),
        "",
        "**Remediation**",
        "",
        _markdown_literal(finding.remediation or "Not specified."),
        "",
        "**Verification**",
        "",
        _markdown_literal(finding.verification or "Not specified."),
        "",
    ]
